name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true


      - name: Fetch Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: export CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.22.1


      - name: Build
        run: |
          cd sideload_webui/
          flutter pub get
          flutter build web  --pwa-strategy none --web-renderer canvaskit --release --base-href "/nbgui/v1/sideload/"

      - name: Copy build files
        run: |
          cd sideload_webui/
          rm build/web/flutter_service_worker.js
          cp build/web ../nonebot_plugin_sideload/ -r
          cd ../

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
